<a href="https://colab.research.google.com/github/karthikoo7/Machine_Learning-BDA-/blob/main/Case_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Case Study : on dataset -- https://www.kaggle.com/datasets/nalisha/early-wakeup-health-and-lifestyle-dataset

In [37]:
import pandas as pd


In [38]:
df = pd.read_csv('/content/early_wakeup_health_dataset.csv')

In [39]:
print(df.shape)
print(df.columns)


(10000, 64)
Index(['Person_ID', 'Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI',
       'Country', 'Occupation', 'Marital_Status', 'Wake_Up_Time', 'Sleep_Time',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Exercise_Type', 'Daily_Steps', 'Morning_Workout', 'Workout_Intensity',
       'Gym_Member', 'Daily_Calorie_Intake', 'Water_Intake_Liters',
       'Fruit_Intake_Per_Day', 'Vegetable_Intake_Per_Day',
       'Protein_Intake_Grams', 'Sugary_Drinks_Per_Week',
       'Fast_Food_Meals_Per_Week', 'Breakfast_Regularity_Score',
       'Smoking_Status', 'Alcohol_Consumption', 'Stress_Level',
       'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day', 'Outdoor_Time_Hours',
       'Social_Interaction_Score', 'Meditation_Practice', 'Resting_Heart_Rate',
       'Systolic_BP', 'Diastol

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 64 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Person_ID                       10000 non-null  object 
 1   Age                             10000 non-null  int64  
 2   Gender                          10000 non-null  object 
 3   Height_cm                       10000 non-null  float64
 4   Weight_kg                       10000 non-null  float64
 5   BMI                             10000 non-null  float64
 6   Country                         10000 non-null  object 
 7   Occupation                      10000 non-null  object 
 8   Marital_Status                  10000 non-null  object 
 9   Wake_Up_Time                    10000 non-null  object 
 10  Sleep_Time                      10000 non-null  object 
 11  Sleep_Duration_Hours            10000 non-null  float64
 12  Sleep_Quality_Score             1

In [41]:
df.head()

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Obesity_Risk,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early_Waker
0,P00001,76,Female,158.8,62.1,24.63,Italy,Entrepreneur,Widowed,08:59,...,Low,High,Medium,Medium,Low,87.3,Excellent,81.8,Excellent,No
1,P00002,49,Female,160.9,68.5,26.45,USA,Freelancer,Single,06:35,...,Medium,Medium,Medium,Low,Medium,72.0,Good,75.2,Good,No
2,P00003,51,Female,151.9,54.8,23.77,Mexico,Nurse,Single,07:31,...,Low,Medium,Medium,Low,Low,75.2,Good,77.1,Good,No
3,P00004,48,Male,167.6,81.3,28.93,Australia,Laborer,Single,08:36,...,Medium,Medium,Low,Low,Medium,82.7,Excellent,87.1,Excellent,No
4,P00005,68,Female,171.9,75.4,25.51,USA,Software Engineer,Married,07:07,...,Medium,High,Medium,Medium,Low,62.7,Average,58.1,Average,No


# Problem Statement:

---
Target : Fitness_Level (Multi class classification)

Drop Columns : ( irrelevent & possible target)
Obesity_Risk
Hypertension_Risk
Diabetes_Risk
Cardiovascular_Risk
Sleep_Disorder_Risk
Health_Score
Healthy_Aging_Score
Wellness_Category
Early_Waker
Depression_Risk_Score
Gym_Member
Height_cm
Weight_kg
Person_ID


Preprocessing :
Wake_Up_Time -->convert to categorical
Sleep_Time -->convert to categorical
Country --> check distribution --> NO NEED OF REMOVAL OF ANY Country -->DONE
Productivity --> to be discussed


Ordinal:
Workout_Intensity
Smoking_Status
Alcohol_Consumption







---



In [42]:
# Drop columns
df.drop(
    columns=[
        "Obesity_Risk",
        "Hypertension_Risk",
        "Diabetes_Risk",
        "Cardiovascular_Risk",
        "Sleep_Disorder_Risk",
        "Health_Score",
        "Healthy_Aging_Score",
        "Wellness_Category",
        "Early_Waker",
        "Depression_Risk_Score",
        "Gym_Member",
        "Height_cm",
        "Weight_kg",
        "Person_ID",
    ],inplace=True

)

df.shape


(10000, 50)

In [43]:
# Converting continous to categorical -- fn= toDateTime

In [44]:
df['Wake_Up_Time'] = pd.to_datetime(df['Wake_Up_Time'])
df['Sleep_Time'] = pd.to_datetime(df['Sleep_Time'])

/tmp/ipykernel_24913/214474565.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Wake_Up_Time'] = pd.to_datetime(df['Wake_Up_Time'])
/tmp/ipykernel_24913/214474565.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Sleep_Time'] = pd.to_datetime(df['Sleep_Time'])


In [45]:
df['Wake_Up_Time'].head()

,Wake_Up_Time
0,2026-06-27 08:59:00
1,2026-06-27 06:35:00
2,2026-06-27 07:31:00
3,2026-06-27 08:36:00
4,2026-06-27 07:07:00


In [46]:
df.loc[(df['Wake_Up_Time'] >= '2026-06-27 04:00:00') &
       (df['Wake_Up_Time'] < '2026-06-27 06:00:00'),"WT_cat"] = 0

df.loc[(df['Wake_Up_Time'] >= '2026-06-27 06:00:00') &
       (df['Wake_Up_Time'] < '2026-06-27 08:00:00'),"WT_cat"] = 1


df.loc[(df['Wake_Up_Time'] >= '2026-06-27 08:00:00') &
       (df['Wake_Up_Time'] < '2026-06-27 10:00:00'),"WT_cat"] = 2


df.loc[(df['Wake_Up_Time'] >= '2026-06-27 10:00:00') &
       (df['Wake_Up_Time'] <= '2026-06-27 11:00:00'),"WT_cat"] = 3

In [47]:
df['WT_cat'].unique()

array([2., 1., 0., 3.])

In [48]:
df.loc[(df['Sleep_Time'] >= '2026-06-27 20:00:00') &
       (df['Sleep_Time'] < '2026-06-27 22:00:00'),"ST_cat"] = 0

df.loc[(df['Sleep_Time'] >= '2026-06-27 22:00:00') &
       (df['Sleep_Time'] <= '2026-06-27 23:59:00'),"ST_cat"] = 1


df.loc[(df['Sleep_Time'] >= '2026-06-27 00:00:00') &
       (df['Sleep_Time'] < '2026-06-27 03:00:00'),"ST_cat"] = 2


df.loc[(df['Sleep_Time'] >= '2026-06-27 03:00:00') &
       (df['Sleep_Time'] < '2026-06-27 07:00:00'),"ST_cat"] = 3


df.loc[(df['Sleep_Time'] >= '2026-06-27 18:00:00') &
       (df['Sleep_Time'] <= '2026-06-27 20:00:00'),"ST_cat"] = 4

In [49]:
df['ST_cat'].unique()

array([2., 1., 0., 4., 3.])

In [50]:
df.drop(columns=['Wake_Up_Time','Sleep_Time'],inplace=True)

In [51]:
df.shape

(10000, 50)

In [52]:
df.columns

Index(['Age', 'Gender', 'BMI', 'Country', 'Occupation', 'Marital_Status',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Exercise_Type', 'Daily_Steps', 'Morning_Workout', 'Workout_Intensity',
       'Daily_Calorie_Intake', 'Water_Intake_Liters', 'Fruit_Intake_Per_Day',
       'Vegetable_Intake_Per_Day', 'Protein_Intake_Grams',
       'Sugary_Drinks_Per_Week', 'Fast_Food_Meals_Per_Week',
       'Breakfast_Regularity_Score', 'Smoking_Status', 'Alcohol_Consumption',
       'Stress_Level', 'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day',
       'Outdoor_Time_Hours', 'Social_Interaction_Score', 'Meditation_Practice',
       'Resting_Heart_Rate', 'Systolic_BP', 'Diastolic_BP',
       'Cholesterol_Level', 'Blood_Sugar_Level', 'Energy_Level_Score',
       'Fatigue_Level_Score', 

In [53]:
df.isna().sum()

,0
Age,0
Gender,0
BMI,0
Country,0
Occupation,0
Marital_Status,0
Sleep_Duration_Hours,0
Sleep_Quality_Score,0
Number_of_Night_Awakenings,0
Weekend_Sleep_Difference_Hours,0


Be carfeul while using mode fn -- when in case of multimodal distribution -- it returns all the modes values -- hence we use -- .iloc[0] to only return to us a single value of mode

In [22]:
#df[['Exercise_Type','Workout_Intensity','Alcohol_Consumption']].mode().iloc[0]

,0
Exercise_Type,Weight Training
Workout_Intensity,Moderate
Alcohol_Consumption,Light


In [26]:
#fill_value = df[['Exercise_Type','Workout_Intensity','Alcohol_Consumption']].mode().iloc[0]

#df[['Exercise_Type','Workout_Intensity','Alcohol_Consumption']].fillna(fill_value,inplace=True)

/tmp/ipykernel_24913/145009578.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Exercise_Type','Workout_Intensity','Alcohol_Consumption']].fillna(fill_value,inplace=True)


In [31]:
df.isnull().sum().sum()

np.int64(4662)

In [54]:
df.loc[df['Alcohol_Consumption'].isna() == True,'Alcohol_Consumption'] = 0

In [55]:
fill_value = df.mode().iloc[0]
df.fillna(fill_value,inplace=True)

In [56]:
df.isnull().sum().sum()

np.int64(0)

# Handle Ordinal Columns by Label Encoding

In [57]:
df['Workout_Intensity'].unique()

array(['Low', 'Moderate', 'High'], dtype=object)

In [58]:
df['Smoking_Status'].unique()

array(['Former', 'Current', 'Never'], dtype=object)

In [59]:
df['Alcohol_Consumption'].unique()

array(['Moderate', 0, 'Light', 'Heavy'], dtype=object)

In [60]:
label_map = {
    'Workout_Intensity':{'Low':0, 'Moderate':1, 'High':2},
    'Smoking_Status':{'Former':0, 'Current':1, 'Never':2},
    'Alcohol_Consumption':{'Moderate':1, 'Light':2, 'Heavy':3}
}

In [61]:
df.replace(label_map,inplace=True)

/tmp/ipykernel_24913/1715271054.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(label_map,inplace=True)


In [68]:
print(df['Workout_Intensity'].unique())
print(df['Smoking_Status'].unique())
print(df['Alcohol_Consumption'].unique())

[0 1 2]
[0 1 2]
[1 0 2 3]


In [71]:
df.columns[df.nunique() > 20] # columns --> continous values

Index(['Age', 'BMI', 'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Weekend_Sleep_Difference_Hours', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Duration_Minutes', 'Daily_Steps', 'Daily_Calorie_Intake',
       'Water_Intake_Liters', 'Protein_Intake_Grams',
       'Breakfast_Regularity_Score', 'Stress_Level', 'Working_Hours_Per_Day',
       'Sitting_Hours_Per_Day', 'Outdoor_Time_Hours',
       'Social_Interaction_Score', 'Resting_Heart_Rate', 'Systolic_BP',
       'Diastolic_BP', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Energy_Level_Score', 'Fatigue_Level_Score', 'Immune_Health_Score',
       'Mood_Score', 'Anxiety_Score', 'Productivity_Score',
       'Focus_Concentration_Score', 'Life_Satisfaction_Score'],
      dtype='object')

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 50 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age                             10000 non-null  int64  
 1   Gender                          10000 non-null  object 
 2   BMI                             10000 non-null  float64
 3   Country                         10000 non-null  object 
 4   Occupation                      10000 non-null  object 
 5   Marital_Status                  10000 non-null  object 
 6   Sleep_Duration_Hours            10000 non-null  float64
 7   Sleep_Quality_Score             10000 non-null  float64
 8   Number_of_Night_Awakenings      10000 non-null  int64  
 9   Weekend_Sleep_Difference_Hours  10000 non-null  float64
 10  Nap_Frequency_Per_Week          10000 non-null  int64  
 11  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 12  Exercise_Frequency_Per_Week     1

# X and Y Split
target = fitnss level

In [72]:
X = df.drop(columns=['Fitness_Level'])
Y = df['Fitness_Level']

X.shape,Y.shape

((10000, 49), (10000,))

In [73]:
Y.unique()

array(['Excellent', 'Good', 'Average', 'Poor'], dtype=object)

In [74]:
label_map = {'Excellent':3, 'Good':2, 'Average':1, 'Poor':0}

Y.replace(label_map,inplace=True)

/tmp/ipykernel_24913/1413044726.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Y.replace(label_map,inplace=True)


In [75]:
Y.unique()

array([3, 2, 1, 0])

In [80]:
X_ohe = pd.get_dummies(X)
X_ohe.shape

(10000, 91)

In [83]:
cat_col = X_ohe.columns[X_ohe.nunique() <= 15]
cat_col.shape

(61,)

In [84]:
cont_col = X_ohe.columns[X_ohe.nunique() > 15]
cont_col.shape

(30,)

Train Test split

In [86]:
from sklearn.model_selection import train_test_split


In [87]:
X_train,X_test,Y_train,Y_test = train_test_split(X_ohe,Y,test_size=0.3,random_state=7,stratify=Y)

X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((7000, 91), (3000, 91), (7000,), (3000,))

applying standard scaler on continous & outlier detection

In [85]:
from sklearn.preprocessing import RobustScaler

In [88]:
rc = RobustScaler()
X_train[cont_col] = rc.fit_transform(X_train[cont_col])
X_test[cont_col] = rc.transform(X_test[cont_col])


Outlier Imputation



In [90]:
def outlier_imputation_iqr(df,col):
  df1 = df.copy()
  q1,q3 = df1[col].quantile([0.25,0.75])
  iqr = q3-q1
  LB = q1 - 1.5*iqr
  UB = q3 + 1.5*iqr
  print("Column -->",col)
  df1.loc[(df1[col]<LB),col] = LB
  df1.loc[(df1[col]>UB),col] = UB
  print(LB,UB, df1[col].min(),df1[col].max())
  return df1

In [91]:
X_train_io = X_train.copy()
for col in cont_col:
  X_train_sc_io = outlier_imputation_iqr(X_train_io,col)

Column --> Age
-1.9642857142857144 2.0357142857142856 -0.8928571428571429 1.3214285714285714
Column --> BMI
-2.0089153046062407 1.9910846953937595 -1.4257057949479945 1.9910846953937595
Column --> Sleep_Duration_Hours
-2.0033557046979866 1.9966442953020134 -2.0033557046979866 1.8523489932885902
Column --> Sleep_Quality_Score
-2.0 2.0 -2.0 1.7272727272727282
Column --> Weekend_Sleep_Difference_Hours
-2.0092592592592595 1.9907407407407407 -1.8888888888888888 1.9907407407407407
Column --> Screen_Time_Before_Bed_Hours
-1.8664122137404582 2.133587786259542 -0.618320610687023 2.133587786259542
Column --> Exercise_Duration_Minutes
-2.0 2.0 -1.6071428571428572 2.0
Column --> Daily_Steps
-2.025921583952065 1.9740784160479354 -1.9954409274456169 1.9740784160479354
Column --> Daily_Calorie_Intake
-1.9973230220107079 2.0026769779892923 -1.9973230220107079 2.0026769779892923
Column --> Water_Intake_Liters
-1.9999999999999996 2.0000000000000004 -1.9999999999999996 2.0000000000000004
Column --> Prote